# Generated by Django 3.2.5 on 2022-08-10 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unseen_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
    ]
