# Generated by Django 3.2.5 on 2022-08-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220814_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
