# Generated by Django 3.2.5 on 2022-08-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authapp.user'),
            preserve_default=False,
        ),
    ]
