# Generated by Django 3.2.5 on 2022-08-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_userdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unseen_posts',
        ),
    ]
