# Generated by Django 3.2.5 on 2022-08-15 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 3, 33, 14, 936005, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
