# Generated by Django 3.2.5 on 2022-08-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220815_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_path',
            field=models.FilePathField(path='/media/posts'),
        ),
    ]
